"""All 109 integration catalog slugs (matches integrations_catalog.py)."""

from __future__ import annotations

CATALOG_INTEGRATIONS: list[tuple[str, str]] = [
    ("github", "GitHub"),
    ("gitlab", "GitLab"),
    ("bitbucket", "Bitbucket"),
    ("vercel", "Vercel"),
    ("netlify", "Netlify"),
    ("render", "Render"),
    ("aws", "AWS"),
    ("google-cloud-platform-gcp", "Google Cloud Platform (GCP)"),
    ("microsoft-azure", "Microsoft Azure"),
    ("docker-registry", "Docker Registry"),
    ("kubernetes-registry", "Kubernetes Registry"),
    ("sentry", "Sentry"),
    ("datadog", "Datadog"),
    ("cloudflare", "Cloudflare"),
    ("postman", "Postman"),
    ("circleci", "CircleCI"),
    ("travis-ci", "Travis CI"),
    ("wordpress", "WordPress"),
    ("webflow", "Webflow"),
    ("wix", "Wix"),
    ("squarespace", "Squarespace"),
    ("ghost", "Ghost"),
    ("strapi", "Strapi"),
    ("contentful", "Contentful"),
    ("sanity", "Sanity"),
    ("salesforce", "Salesforce"),
    ("hubspot", "HubSpot"),
    ("zoho-crm", "Zoho CRM"),
    ("pipedrive", "Pipedrive"),
    ("highlevel-gohighlevel", "HighLevel (GoHighLevel)"),
    ("activecampaign", "ActiveCampaign"),
    ("keap-infusionsoft", "Keap (Infusionsoft)"),
    ("dynamics-365", "Dynamics 365"),
    ("gong", "Gong"),
    ("chorus", "Chorus"),
    ("zendesk", "Zendesk"),
    ("intercom", "Intercom"),
    ("freshdesk", "Freshdesk"),
    ("help-scout", "Help Scout"),
    ("servicenow", "ServiceNow"),
    ("gorgias", "Gorgias"),
    ("front", "Front"),
    ("postgresql", "PostgreSQL"),
    ("mysql", "MySQL"),
    ("mongodb", "MongoDB"),
    ("redis", "Redis"),
    ("supabase", "Supabase"),
    ("firebase", "Firebase"),
    ("snowflake", "Snowflake"),
    ("google-bigquery", "Google BigQuery"),
    ("amazon-redshift", "Amazon Redshift"),
    ("elasticsearch", "Elasticsearch"),
    ("pinecone", "Pinecone"),
    ("weaviate", "Weaviate"),
    ("qdrant", "Qdrant"),
    ("chromadb", "ChromaDB"),
    ("milvus", "Milvus"),
    ("neo4j", "Neo4j"),
    ("amazon-s3", "Amazon S3"),
    ("google-cloud-storage", "Google Cloud Storage"),
    ("slack", "Slack"),
    ("microsoft-teams", "Microsoft Teams"),
    ("discord", "Discord"),
    ("telegram", "Telegram"),
    ("whatsapp-business-api", "WhatsApp Business API"),
    ("twilio", "Twilio"),
    ("sendgrid", "SendGrid"),
    ("postmark", "Postmark"),
    ("mailchimp", "Mailchimp"),
    ("jira", "Jira"),
    ("asana", "Asana"),
    ("trello", "Trello"),
    ("linear", "Linear"),
    ("clickup", "ClickUp"),
    ("mondaycom", "Monday.com"),
    ("basecamp", "Basecamp"),
    ("notion", "Notion"),
    ("confluence", "Confluence"),
    ("coda", "Coda"),
    ("zapier", "Zapier"),
    ("make-integromat", "Make (Integromat)"),
    ("n8n", "n8n"),
    ("pipedream", "Pipedream"),
    ("shopify", "Shopify"),
    ("woocommerce", "WooCommerce"),
    ("bigcommerce", "BigCommerce"),
    ("magento-adobe-commerce", "Magento (Adobe Commerce)"),
    ("amazon-seller-central", "Amazon Seller Central"),
    ("ebay-api", "eBay API"),
    ("etsy-api", "Etsy API"),
    ("square", "Square"),
    ("stripe", "Stripe"),
    ("paypal", "PayPal"),
    ("brex", "Brex"),
    ("quickbooks-online", "QuickBooks Online"),
    ("xero", "Xero"),
    ("netsuite", "Netsuite"),
    ("sap", "SAP"),
    ("billcom", "Bill.com"),
    ("chargebee", "Chargebee"),
    ("recurly", "Recurly"),
    ("google-workspace-gmail-docs-drive-sheets-calendar", "Google Workspace (Gmail, Docs, Drive, Sheets, Calendar)"),
    ("microsoft-365-outlook-onedrive-sharepoint-excel", "Microsoft 365 (Outlook, OneDrive, SharePoint, Excel)"),
    ("airtable", "Airtable"),
    ("calendly", "Calendly"),
    ("docusign", "DocuSign"),
    ("pandadoc", "PandaDoc"),
    ("zoom", "Zoom"),
    ("google-meet", "Google Meet"),
]
